parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
- react
env:
  browser: true
  node: true
  es6: true
extends:
- standard
- plugin:react/recommended
- plugin:import/errors
rules:
  no-unused-vars:
  - 1
  space-before-function-paren:
  - 0
  prefer-const: 2